spring:
 application:
   name: Config-Default

eureka:
 instance:
 appname: ${spring.application.name}
   prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://localhost:8761/eureka
